### PR TITLE
Add selected facet component

### LINKED ISSUE #35: Implement Selected Facet
Which is like "selected item", but doesn't have a border.  It should be used for filters for blacklight apps.

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #35

### CODE REVIEW

**Comment by dnoneill** [comment]
@jcoyne Looks mostly good. When I tested this in earthworks I noticed the off center is back so I think we need to add the flex in.

I think this is happening because we are decreasing the padding-y and it is making the lack to centering more noticable. I tried in Chrome (version 128.0.6613.85, which says its up to date). So I think this might be an issue.

With --padding-y set to default
Screenshot 2024-08-27 at 5 39 32 PM

With --padding-x set to .25rem
Screenshot 2024-08-27 at 5 39 44 PM

**Comment by jcoyne** [comment]
@dnoneill do you have a branch to share?

**Comment by dnoneill** [comment]
@jcoyne I copied the CSS into earthworks.css on this branch https://github.com/sul-dlss/earthworks/pull/1221

**Comment by jcoyne** [comment]
@dnoneill I think the problem there is that Earthworks is putting it into a line that also has the "Start over" button.  The start over button is pushing up the line height, so the selected facet component is growing to match that size.   I think we need to think of this more expansively.  E.g. Do we want the "Start over" button to be taller than the selected facet buttons?

**Comment by dnoneill** [comment]
@jcoyne I tested locally and you are right about the start over button causing the issue. I think this okay to merge and I can solve the problem in the constraints_component

**Review by dnoneill — APPROVED** [review]

**Comment by dnoneill** [comment]
@jcoyne I opened https://github.com/sul-dlss/component-library/pull/45 which solves the problem in earthworks. It also fixes the fact we don't have button padding defined correctly in the component library.

**Pull request merged**
