### PR TITLE
Update palette.css

### PR DESCRIPTION
**Pull request by dnoneill**

### CODE REVIEW

**Review by jcoyne — COMMENTED** [review]
I don't think we want to add colors here that are not used in any of the components.

**Comment by jcoyne** [comment]
Argo has a section of colors that are no in the component library. Perhaps you could do something like this:
https://github.com/sul-dlss/argo/blob/main/app/assets/stylesheets/variables.css#L2-L9

**Comment by dnoneill** [comment]
Is there a reason why not? I am thinking it would be nice to have all the standard Stanford colors set in one place so we don't have to keep updating them in different apps. Maybe we shouldn't but I see value in having all the colors standardized and in on place.

**Comment by jcoyne** [comment]
All the colors * all the variants * rgb + hex seems like a lot of css  and it may not ever be used.  This would make it harder to maintain because we don't know if or where any of these things may be used.  I think a minimal set could be better.

**Comment by dnoneill** [comment]
Good point. We are going to use this for earthworks but I see your point.

**Pull request closed without merging**
