### PR TITLE
Add new SUL logo

### LINKED ISSUE #55: New SUL logo
Update SUL logo in the header and footer. SVG files [here](https://stanfordlib.slack.com/archives/C07CQLENZGW/p1731697585525749).

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #55

### CODE REVIEW

**Comment by dnoneill** [comment]
This mostly looks good. I am attaching screenshots for reference. I am guessing @alundgard @dbranchini @astridu might want to review for UX. One issue I am seeing is in the mobile footer. The icon should still show up just above the links, at least that is current behavior.

Screenshot 2024-11-20 at 4 19 56 PM
Screenshot 2024-11-20 at 4 20 16 PM
Screenshot 2024-11-20 at 4 20 57 PM
Screenshot 2024-11-20 at 4 19 50 PM

**Comment by alundgard** [comment]
Thanks for the screenshots. I'm also not seeing the new logo (in either the header or footer) when I checkout this branch locally. But I do see the original logo on main.

**Comment by jcoyne** [comment]
@alundgard you have to run it via a webserver. The browser prevents loading from the file system due to CORS restrictions.

**Comment by jcoyne** [comment]
@dnoneill I added a fix for the footer.

**Review by dnoneill — APPROVED** [review]

**Comment by alundgard** [comment]
It looks like the width of the logo container is unchanged, and since the new logo is longer, the entire logo gets shrunk to fit the container?

header - before
header - after
footer - before
footer - after

Would it be possible to increase the logo container width so that the "Stanford" font appears to be roughly the same size?

I updated the Figma designs for the [Header](https://www.figma.com/design/K1syTsalaB1nlRftgOi0Pw/DLSS-Components?node-id=284-724&t=liBU8AYeJutHZovn-4) and [Footer](https://www.figma.com/design/K1syTsalaB1nlRftgOi0Pw/DLSS-Components?node-id=111-172&t=liBU8AYeJutHZovn-4) so that the width of the logo container is 280.

**Comment by jcoyne** [comment]
@alundgard it's set to 280px now.

**Pull request merged**
